package main

import (
	likeusecase "like-api/internal/application/usecases/like"
	postusecase "like-api/internal/application/usecases/post"
	userusecase "like-api/internal/application/usecases/user"
	"like-api/internal/infrastructure/database/memory"
	"like-api/internal/infrastructure/router"
	httpHandler "like-api/internal/interfaces/http"

	_ "like-api/docs" // This will be generated by swag
)

func main() {
	// Initialize repositories
	userRepo := memory.NewUserRepository()
	postRepo := memory.NewPostRepository()
	likeRepo := memory.NewLikeRepository()

	// Initialize with hardcoded data
	memory.InitData(userRepo, postRepo, likeRepo)

	// Initialize use cases
	getUsersUseCase := userusecase.NewGetUsersUseCase(userRepo)
	getPostsUseCase := postusecase.NewGetPostsUseCase(postRepo)
	getUserPostsUseCase := postusecase.NewGetUserPostsUseCase(userRepo, postRepo)
	getPostLikesUseCase := postusecase.NewGetPostLikesUseCase(postRepo, likeRepo)
	likePostUseCase := likeusecase.NewLikePostUseCase(userRepo, postRepo, likeRepo)
	unlikePostUseCase := likeusecase.NewUnlikePostUseCase(postRepo, likeRepo)
	getUserLikedPostsUseCase := likeusecase.NewGetUserLikedPostsUseCase(userRepo, postRepo, likeRepo)

	// Initialize handlers
	userHandler := httpHandler.NewUserHandler(getUsersUseCase)
	postHandler := httpHandler.NewPostHandler(getPostsUseCase, getUserPostsUseCase, getPostLikesUseCase)
	likeHandler := httpHandler.NewLikeHandler(likePostUseCase, unlikePostUseCase, getUserLikedPostsUseCase)

	// Setup router
	r := router.NewRouter(userHandler, postHandler, likeHandler)
	router := r.Setup()

	// Start server
	router.Run(":8080")
}
