package main

import (
	"net/http"

	"github.com/gin-contrib/cors"
	"github.com/gin-gonic/gin"
	"github.com/google/uuid"
	swaggerFiles "github.com/swaggo/files"
	ginSwagger "github.com/swaggo/gin-swagger"

	"like-api/internal/domain/entities"
	"like-api/internal/domain/repositories"
	"like-api/internal/infrastructure/database/memory"

	_ "like-api/docs" // This will be generated by swag
)

// @title           Like API
// @version         1.0
// @description     API for liking posts with predefined users and posts
// @host            localhost:8080
// @BasePath        /api/v1

// App holds the application state
type App struct {
	userRepo repositories.UserRepository
	postRepo repositories.PostRepository
	likeRepo repositories.LikeRepository
}

// Global app instance
var app *App

// LikePostRequest represents the request body for liking a post
type LikePostRequest struct {
	UserID string `json:"user_id" binding:"required" example:"user1"`
	PostID string `json:"post_id" binding:"required" example:"post1"`
}

// UnlikePostRequest represents the request body for unliking a post
type UnlikePostRequest struct {
	UserID string `json:"user_id" binding:"required" example:"user1"`
	PostID string `json:"post_id" binding:"required" example:"post1"`
}

// Response represents a standard API response
type Response struct {
	Success bool        `json:"success"`
	Message string      `json:"message,omitempty"`
	Data    interface{} `json:"data,omitempty"`
}

// @Summary Get all users
// @Description Get list of all predefined users
// @Tags users
// @Accept json
// @Produce json
// @Success 200 {object} Response
// @Router /users [get]
func getUsers(c *gin.Context) {
	users, err := app.userRepo.FindAll()
	if err != nil {
		c.JSON(http.StatusInternalServerError, Response{Success: false, Message: "Failed to fetch users"})
		return
	}
	c.JSON(http.StatusOK, Response{Success: true, Data: users})
}

// @Summary Get all posts
// @Description Get list of all posts
// @Tags posts
// @Accept json
// @Produce json
// @Success 200 {object} Response
// @Router /posts [get]
func getPosts(c *gin.Context) {
	posts, err := app.postRepo.FindAll()
	if err != nil {
		c.JSON(http.StatusInternalServerError, Response{Success: false, Message: "Failed to fetch posts"})
		return
	}
	c.JSON(http.StatusOK, Response{Success: true, Data: posts})
}

// @Summary Get posts by user
// @Description Get all posts from a specific user
// @Tags posts
// @Accept json
// @Produce json
// @Param user_id path string true "User ID"
// @Success 200 {object} Response
// @Failure 404 {object} Response
// @Router /users/{user_id}/posts [get]
func getUserPosts(c *gin.Context) {
	userID := c.Param("user_id")

	// Check if user exists
	if !app.userRepo.Exists(userID) {
		c.JSON(http.StatusNotFound, Response{Success: false, Message: "User not found"})
		return
	}

	posts, err := app.postRepo.FindByUserID(userID)
	if err != nil {
		c.JSON(http.StatusInternalServerError, Response{Success: false, Message: "Failed to fetch posts"})
		return
	}
	c.JSON(http.StatusOK, Response{Success: true, Data: posts})
}

// @Summary Like a post
// @Description Like a specific post as a user
// @Tags likes
// @Accept json
// @Produce json
// @Param like body LikePostRequest true "Like request"
// @Success 200 {object} Response
// @Failure 400 {object} Response
// @Failure 404 {object} Response
// @Failure 409 {object} Response
// @Router /likes [post]
func likePost(c *gin.Context) {
	var req LikePostRequest
	if err := c.ShouldBindJSON(&req); err != nil {
		c.JSON(http.StatusBadRequest, Response{Success: false, Message: "Invalid request: " + err.Error()})
		return
	}

	// Check if user exists
	if !app.userRepo.Exists(req.UserID) {
		c.JSON(http.StatusNotFound, Response{Success: false, Message: "User not found"})
		return
	}

	// Check if post exists
	post, err := app.postRepo.FindByID(req.PostID)
	if err != nil {
		c.JSON(http.StatusNotFound, Response{Success: false, Message: "Post not found"})
		return
	}

	// Check if already liked
	if app.likeRepo.Exists(req.UserID, req.PostID) {
		c.JSON(http.StatusConflict, Response{Success: false, Message: "Post already liked by this user"})
		return
	}

	// Create like
	likeID := uuid.New().String()
	like := entities.Like{
		ID:        likeID,
		UserID:    req.UserID,
		PostID:    req.PostID,
		CreatedAt: "2024-01-20T10:00:00Z", // In real app, use time.Now()
	}

	if err := app.likeRepo.Create(like); err != nil {
		c.JSON(http.StatusInternalServerError, Response{Success: false, Message: "Failed to create like"})
		return
	}

	// Update post like count
	post.Likes++
	if err := app.postRepo.Update(post); err != nil {
		c.JSON(http.StatusInternalServerError, Response{Success: false, Message: "Failed to update post"})
		return
	}

	c.JSON(http.StatusOK, Response{
		Success: true,
		Message: "Post liked successfully",
		Data:    like,
	})
}

// @Summary Unlike a post
// @Description Remove like from a post
// @Tags likes
// @Accept json
// @Produce json
// @Param unlike body UnlikePostRequest true "Unlike request"
// @Success 200 {object} Response
// @Failure 400 {object} Response
// @Failure 404 {object} Response
// @Router /likes [delete]
func unlikePost(c *gin.Context) {
	var req UnlikePostRequest
	if err := c.ShouldBindJSON(&req); err != nil {
		c.JSON(http.StatusBadRequest, Response{Success: false, Message: "Invalid request: " + err.Error()})
		return
	}

	// Check if the like exists
	if !app.likeRepo.Exists(req.UserID, req.PostID) {
		c.JSON(http.StatusNotFound, Response{Success: false, Message: "Like not found"})
		return
	}

	// Delete the like
	if err := app.likeRepo.Delete(req.UserID, req.PostID); err != nil {
		c.JSON(http.StatusInternalServerError, Response{Success: false, Message: "Failed to delete like"})
		return
	}

	// Update post like count
	post, err := app.postRepo.FindByID(req.PostID)
	if err == nil {
		post.Likes--
		app.postRepo.Update(post)
	}

	c.JSON(http.StatusOK, Response{
		Success: true,
		Message: "Post unliked successfully",
	})
}

// @Summary Get likes for a post
// @Description Get all likes for a specific post
// @Tags likes
// @Accept json
// @Produce json
// @Param post_id path string true "Post ID"
// @Success 200 {object} Response
// @Failure 404 {object} Response
// @Router /posts/{post_id}/likes [get]
func getPostLikes(c *gin.Context) {
	postID := c.Param("post_id")

	// Check if post exists
	if !app.postRepo.Exists(postID) {
		c.JSON(http.StatusNotFound, Response{Success: false, Message: "Post not found"})
		return
	}

	likes, err := app.likeRepo.FindByPostID(postID)
	if err != nil {
		c.JSON(http.StatusInternalServerError, Response{Success: false, Message: "Failed to fetch likes"})
		return
	}
	c.JSON(http.StatusOK, Response{Success: true, Data: likes})
}

// @Summary Get user's liked posts
// @Description Get all posts liked by a specific user
// @Tags likes
// @Accept json
// @Produce json
// @Param user_id path string true "User ID"
// @Success 200 {object} Response
// @Failure 404 {object} Response
// @Router /users/{user_id}/liked-posts [get]
func getUserLikedPosts(c *gin.Context) {
	userID := c.Param("user_id")

	// Check if user exists
	if !app.userRepo.Exists(userID) {
		c.JSON(http.StatusNotFound, Response{Success: false, Message: "User not found"})
		return
	}

	// Get all likes by user
	likes, err := app.likeRepo.FindByUserID(userID)
	if err != nil {
		c.JSON(http.StatusInternalServerError, Response{Success: false, Message: "Failed to fetch likes"})
		return
	}

	// Get the actual posts
	likedPosts := make([]entities.Post, 0)
	for _, like := range likes {
		if post, err := app.postRepo.FindByID(like.PostID); err == nil {
			likedPosts = append(likedPosts, post)
		}
	}
	c.JSON(http.StatusOK, Response{Success: true, Data: likedPosts})
}

func main() {
	// Initialize app with hardcoded data
	userRepo := memory.NewUserRepository()
	postRepo := memory.NewPostRepository()
	likeRepo := memory.NewLikeRepository()

	// Initialize with hardcoded data
	memory.InitData(userRepo, postRepo, likeRepo)

	app = &App{
		userRepo: userRepo,
		postRepo: postRepo,
		likeRepo: likeRepo,
	}

	// Setup Gin router
	router := gin.Default()

	router.Use(cors.Default())

	// API routes
	api := router.Group("/api/v1")
	{
		// User routes
		api.GET("/users", getUsers)
		api.GET("/users/:user_id/posts", getUserPosts)
		api.GET("/users/:user_id/liked-posts", getUserLikedPosts)

		// Post routes
		api.GET("/posts", getPosts)
		api.GET("/posts/:post_id/likes", getPostLikes)

		// Like routes
		api.POST("/likes", likePost)
		api.DELETE("/likes", unlikePost)
	}

	// Swagger documentation
	router.GET("/swagger/*any", ginSwagger.WrapHandler(swaggerFiles.Handler))

	// Start server
	router.Run(":8080")
}
