package main

import (
	"net/http"
	"sync"

	"github.com/gin-contrib/cors"
	"github.com/gin-gonic/gin"
	"github.com/google/uuid"
	swaggerFiles "github.com/swaggo/files"
	ginSwagger "github.com/swaggo/gin-swagger"

	"like-api/internal/domain/entities"

	_ "like-api/docs" // This will be generated by swag
)

// @title           Like API
// @version         1.0
// @description     API for liking posts with predefined users and posts
// @host            localhost:8080
// @BasePath        /api/v1

// App holds the application state
type App struct {
	users map[string]entities.User
	posts map[string]entities.Post
	likes map[string]entities.Like
	mu    sync.RWMutex
}

// Global app instance
var app *App

// initData initializes hardcoded users and posts
func initData() *App {
	app := &App{
		users: make(map[string]entities.User),
		posts: make(map[string]entities.Post),
		likes: make(map[string]entities.Like),
	}

	// Hardcoded users
	users := []entities.User{
		{ID: "user1", Username: "john_doe", Name: "John Doe", Email: "john@example.com"},
		{ID: "user2", Username: "jane_smith", Name: "Jane Smith", Email: "jane@example.com"},
		{ID: "user3", Username: "bob_wilson", Name: "Bob Wilson", Email: "bob@example.com"},
	}

	for _, user := range users {
		app.users[user.ID] = user
	}

	// Hardcoded posts for each user
	posts := []entities.Post{
		// John's posts
		{ID: "post1", UserID: "user1", Title: "First Post!", Content: "Hello everyone! This is my first post.", Likes: 0},
		{ID: "post2", UserID: "user1", Title: "Go Programming", Content: "Learning Go is amazing!", Likes: 0},

		// Jane's posts
		{ID: "post3", UserID: "user2", Title: "Travel Diary", Content: "Just visited Paris! 🗼", Likes: 0},
		{ID: "post4", UserID: "user2", Title: "Cooking Tips", Content: "Here's my favorite pasta recipe", Likes: 0},
		{ID: "post5", UserID: "user2", Title: "Fitness Journey", Content: "Day 30 of my workout challenge", Likes: 0},

		// Bob's posts
		{ID: "post6", UserID: "user3", Title: "Tech News", Content: "New iPhone just dropped!", Likes: 0},
		{ID: "post7", UserID: "user3", Title: "Gaming", Content: "Just finished Elden Ring", Likes: 0},
	}

	for _, post := range posts {
		app.posts[post.ID] = post
	}

	// Add some pre-existing likes for demo
	preLikes := []entities.Like{
		{ID: uuid.New().String(), UserID: "user1", PostID: "post1", CreatedAt: "2024-01-16T09:00:00Z"},
		{ID: uuid.New().String(), UserID: "user2", PostID: "post2", CreatedAt: "2024-01-15T10:00:00Z"},
		{ID: uuid.New().String(), UserID: "user3", PostID: "post3", CreatedAt: "2024-01-15T11:00:00Z"},
	}

	for _, like := range preLikes {
		app.likes[like.ID] = like
		// Update post like count
		if post, exists := app.posts[like.PostID]; exists {
			post.Likes++
			app.posts[like.PostID] = post
		}
	}

	return app
}

// LikePostRequest represents the request body for liking a post
type LikePostRequest struct {
	UserID string `json:"user_id" binding:"required" example:"user1"`
	PostID string `json:"post_id" binding:"required" example:"post1"`
}

// UnlikePostRequest represents the request body for unliking a post
type UnlikePostRequest struct {
	UserID string `json:"user_id" binding:"required" example:"user1"`
	PostID string `json:"post_id" binding:"required" example:"post1"`
}

// Response represents a standard API response
type Response struct {
	Success bool        `json:"success"`
	Message string      `json:"message,omitempty"`
	Data    interface{} `json:"data,omitempty"`
}

// @Summary Get all users
// @Description Get list of all predefined users
// @Tags users
// @Accept json
// @Produce json
// @Success 200 {object} Response
// @Router /users [get]
func getUsers(c *gin.Context) {
	app.mu.RLock()
	defer app.mu.RUnlock()

	users := make([]entities.User, 0, len(app.users))
	for _, user := range app.users {
		users = append(users, user)
	}
	c.JSON(http.StatusOK, Response{Success: true, Data: users})
}

// @Summary Get all posts
// @Description Get list of all posts
// @Tags posts
// @Accept json
// @Produce json
// @Success 200 {object} Response
// @Router /posts [get]
func getPosts(c *gin.Context) {
	app.mu.RLock()
	defer app.mu.RUnlock()

	posts := make([]entities.Post, 0, len(app.posts))
	for _, post := range app.posts {
		posts = append(posts, post)
	}
	c.JSON(http.StatusOK, Response{Success: true, Data: posts})
}

// @Summary Get posts by user
// @Description Get all posts from a specific user
// @Tags posts
// @Accept json
// @Produce json
// @Param user_id path string true "User ID"
// @Success 200 {object} Response
// @Failure 404 {object} Response
// @Router /users/{user_id}/posts [get]
func getUserPosts(c *gin.Context) {
	userID := c.Param("user_id")

	app.mu.RLock()
	defer app.mu.RUnlock()

	// Check if user exists
	if _, exists := app.users[userID]; !exists {
		c.JSON(http.StatusNotFound, Response{Success: false, Message: "User not found"})
		return
	}

	posts := make([]entities.Post, 0)
	for _, post := range app.posts {
		if post.UserID == userID {
			posts = append(posts, post)
		}
	}
	c.JSON(http.StatusOK, Response{Success: true, Data: posts})
}

// @Summary Like a post
// @Description Like a specific post as a user
// @Tags likes
// @Accept json
// @Produce json
// @Param like body LikePostRequest true "Like request"
// @Success 200 {object} Response
// @Failure 400 {object} Response
// @Failure 404 {object} Response
// @Failure 409 {object} Response
// @Router /likes [post]
func likePost(c *gin.Context) {
	var req LikePostRequest
	if err := c.ShouldBindJSON(&req); err != nil {
		c.JSON(http.StatusBadRequest, Response{Success: false, Message: "Invalid request: " + err.Error()})
		return
	}

	app.mu.Lock()
	defer app.mu.Unlock()

	// Check if user exists
	if _, exists := app.users[req.UserID]; !exists {
		c.JSON(http.StatusNotFound, Response{Success: false, Message: "User not found"})
		return
	}

	// Check if post exists
	post, exists := app.posts[req.PostID]
	if !exists {
		c.JSON(http.StatusNotFound, Response{Success: false, Message: "Post not found"})
		return
	}

	// Check if already liked
	for _, like := range app.likes {
		if like.UserID == req.UserID && like.PostID == req.PostID {
			c.JSON(http.StatusConflict, Response{Success: false, Message: "Post already liked by this user"})
			return
		}
	}

	// Create like
	likeID := uuid.New().String()
	like := entities.Like{
		ID:        likeID,
		UserID:    req.UserID,
		PostID:    req.PostID,
		CreatedAt: "2024-01-20T10:00:00Z", // In real app, use time.Now()
	}
	app.likes[likeID] = like

	// Update post like count
	post.Likes++
	app.posts[req.PostID] = post

	c.JSON(http.StatusOK, Response{
		Success: true,
		Message: "Post liked successfully",
		Data:    like,
	})
}

// @Summary Unlike a post
// @Description Remove like from a post
// @Tags likes
// @Accept json
// @Produce json
// @Param unlike body UnlikePostRequest true "Unlike request"
// @Success 200 {object} Response
// @Failure 400 {object} Response
// @Failure 404 {object} Response
// @Router /likes [delete]
func unlikePost(c *gin.Context) {
	var req UnlikePostRequest
	if err := c.ShouldBindJSON(&req); err != nil {
		c.JSON(http.StatusBadRequest, Response{Success: false, Message: "Invalid request: " + err.Error()})
		return
	}

	app.mu.Lock()
	defer app.mu.Unlock()

	// Find and remove the like
	var likeToDelete string
	for id, like := range app.likes {
		if like.UserID == req.UserID && like.PostID == req.PostID {
			likeToDelete = id
			break
		}
	}

	if likeToDelete == "" {
		c.JSON(http.StatusNotFound, Response{Success: false, Message: "Like not found"})
		return
	}

	delete(app.likes, likeToDelete)

	// Update post like count
	if post, exists := app.posts[req.PostID]; exists {
		post.Likes--
		app.posts[req.PostID] = post
	}

	c.JSON(http.StatusOK, Response{
		Success: true,
		Message: "Post unliked successfully",
	})
}

// @Summary Get likes for a post
// @Description Get all likes for a specific post
// @Tags likes
// @Accept json
// @Produce json
// @Param post_id path string true "Post ID"
// @Success 200 {object} Response
// @Failure 404 {object} Response
// @Router /posts/{post_id}/likes [get]
func getPostLikes(c *gin.Context) {
	postID := c.Param("post_id")

	app.mu.RLock()
	defer app.mu.RUnlock()

	// Check if post exists
	if _, exists := app.posts[postID]; !exists {
		c.JSON(http.StatusNotFound, Response{Success: false, Message: "Post not found"})
		return
	}

	likes := make([]entities.Like, 0)
	for _, like := range app.likes {
		if like.PostID == postID {
			likes = append(likes, like)
		}
	}
	c.JSON(http.StatusOK, Response{Success: true, Data: likes})
}

// @Summary Get user's liked posts
// @Description Get all posts liked by a specific user
// @Tags likes
// @Accept json
// @Produce json
// @Param user_id path string true "User ID"
// @Success 200 {object} Response
// @Failure 404 {object} Response
// @Router /users/{user_id}/liked-posts [get]
func getUserLikedPosts(c *gin.Context) {
	userID := c.Param("user_id")

	app.mu.RLock()
	defer app.mu.RUnlock()

	// Check if user exists
	if _, exists := app.users[userID]; !exists {
		c.JSON(http.StatusNotFound, Response{Success: false, Message: "User not found"})
		return
	}

	likedPosts := make([]entities.Post, 0)
	for _, like := range app.likes {
		if like.UserID == userID {
			if post, exists := app.posts[like.PostID]; exists {
				likedPosts = append(likedPosts, post)
			}
		}
	}
	c.JSON(http.StatusOK, Response{Success: true, Data: likedPosts})
}

func main() {
	// Initialize app with hardcoded data
	app = initData()

	// Setup Gin router
	router := gin.Default()

	router.Use(cors.Default())

	// API routes
	api := router.Group("/api/v1")
	{
		// User routes
		api.GET("/users", getUsers)
		api.GET("/users/:user_id/posts", getUserPosts)
		api.GET("/users/:user_id/liked-posts", getUserLikedPosts)

		// Post routes
		api.GET("/posts", getPosts)
		api.GET("/posts/:post_id/likes", getPostLikes)

		// Like routes
		api.POST("/likes", likePost)
		api.DELETE("/likes", unlikePost)
	}

	// Swagger documentation
	router.GET("/swagger/*any", ginSwagger.WrapHandler(swaggerFiles.Handler))

	// Start server
	router.Run(":8080")
}
